// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pywqnxuprfefbxgcvdtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5d3FueHVwcmZlZmJ4Z2N2ZHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzU1OTYsImV4cCI6MjA3MTUxMTU5Nn0.zd92EXnv17rLRSAWQJcRlenMyAxYLNZLcQKm7ctksKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});